---
title: "Data Transformation"
execute: 
  eval: true
  freeze: true
---

```{r, setup}
#| include: false

library(dplyr)
library(dbplyr)
library(DBI)
```

## Catch up {.unumbered}

```{r}
library(dplyr)
library(dbplyr)
library(DBI)

con <- dbConnect(
  odbc::databricks(),
  HTTPPath = "/sql/1.0/warehouses/300bd24ba12adf8e"
)

customers <- tbl(con, I("samples.tpch.customer"))
nation <- tbl(con, I("samples.tpch.nation"))
```

## Prepare base 

```{r}
orders <- tbl(con, I("samples.tpch.orders"))
```

```{r}
orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey"))
```

```{r}
orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey")) %>% 
  left_join(nation, by = c("c_nationkey" = "n_nationkey"))
```

```{r}
orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey")) %>% 
  left_join(nation, by = c("c_nationkey" = "n_nationkey")) %>% 
  mutate(customer = o_custkey, order_year = year(o_orderdate), order_month = month(o_orderdate))
```
```{r}
orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey")) %>% 
  left_join(nation, by = c("c_nationkey" = "n_nationkey")) %>% 
  mutate(customer = o_custkey, order_year = year(o_orderdate), order_month = month(o_orderdate)) %>% 
  select(customer, everything()) 
```

```{r}
orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey")) %>% 
  left_join(nation, by = c("c_nationkey" = "n_nationkey")) %>% 
  mutate(customer = o_custkey, order_year = year(o_orderdate), order_month = month(o_orderdate)) %>% 
  select(customer, everything(), -ends_with("comment")) 
```

```{r}
orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey")) %>% 
  left_join(nation, by = c("c_nationkey" = "n_nationkey")) %>% 
  mutate(customer = o_custkey, order_year = year(o_orderdate), order_month = month(o_orderdate)) %>% 
  select(customer, everything(), -ends_with("comment"), -ends_with("key")) 
```


```{r}
prep_orders <- orders %>% 
  left_join(customers, by = c("o_custkey" = "c_custkey")) %>% 
  left_join(nation, by = c("c_nationkey" = "n_nationkey")) %>% 
  mutate(customer = o_custkey, order_year = year(o_orderdate), order_month = month(o_orderdate)) %>% 
  select(customer, everything(), -ends_with("comment"), -ends_with("key")) 
```

```{r}
prep_orders %>% 
  glimpse()
```
```{r}
prep_orders %>% 
  group_by(n_name) %>% 
  summarise(
    total_price = sum(o_totalprice, na.rm = TRUE)
  ) %>% 
  arrange(desc(total_price))
```


```{r}
prep_orders %>% 
  filter(order_year == 1998) %>% 
  group_by(n_name) %>% 
  summarise(
    total_price = sum(o_totalprice, na.rm = TRUE)
  ) %>% 
  arrange(desc(total_price))
```

```{r}
prep_orders %>% 
  group_by(n_name, order_year) %>% 
  summarise(
    total_price = sum(o_totalprice, na.rm = TRUE)
  ) %>% 
  group_by(order_year) %>% 
  filter(total_price == max(total_price))
```

```{r}
prep_orders %>% 
  group_by(customer) %>% 
  summarise(
    total_price = sum(o_totalprice, na.rm = TRUE)
    ) %>% 
  arrange(desc(total_price))
```

```{r}
prep_orders %>% 
  group_by(customer) %>% 
  summarise(
    country = first(n_name), 
    segment = first(c_mktsegment),
    total_price = sum(o_totalprice, na.rm = TRUE)
    ) %>% 
  arrange(desc(total_price))
```

