project:
  type: book

book:
  chapters:
    - index.qmd
    - part: odbc.qmd
      chapters:
      - 01-connecting-interacting.qmd
      - 02-remote-processing.qmd
      - 03-preparing-exploring.qmd
      - 04-visualizations.qmd
      - 08-dashboards.qmd
      - r-udfs-modeling.qmd
format:
  html:
    toc: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"     