project:
  type: book

book:
  chapters:
    - index.qmd
    - part: odbc.qmd
      chapters:
      - 01-connecting-interacting.qmd
      - 02-remote-processing.qmd
      - 03-more-dplyr-dbplyr.qmd
format:
  html:
    toc: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"     