project:
  type: book
  output-dir: ../../docs

book:
  chapters:
    - index.qmd
    - connecting.qmd
    - remote-processing.qmd
    - preparing-exploring.qmd
    - visualizations.qmd
    - databricks.qmd
    - r-udfs.qmd
    - r-udfs-modeling.qmd
    - dashboards.qmd
format:
  html:
    toc: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"     