---
format:
  html:
    toc: false
---
# Using R with Databricks  {.unnumbered}

As most organization’s data migrate to the cloud, the ability to analyze data 
in-place becomes more important. This workshop will walk you through how to
think about remote data, how to access it, and how to analyze it efficiently. 
We will review the latest in integrations between R and Databricks. The two 
integrations that we will review are:

- Spark via Databricks Connect

- ODBC connection

During the workshop, we will discuss best practices for when to use which
integration, as well as techniques to take your analysis into production.

This course is for you if you:

- Are an R user

- Plan, or are currently, using Databricks services

- Need to learn how to access and analyze data in Databricks

Link to the presentation: [Using Databricks with R](using-databricks-with-r.html){target="_blank"}

```{r}
#| eval: true
#| include: false

quarto::quarto_render("../slides/using-databricks-with-r.qmd")

library(fs)
file_copy("../slides/using-databricks-with-r.html", "../../docs", overwrite = TRUE)
dir_copy(
  "../slides/using-databricks-with-r_files", 
  "../../docs/using-databricks-with-r_files", 
  overwrite = TRUE
  )
dir_copy("../slides/assets", "../../docs/assets", overwrite = TRUE)
```

